services:
  anpr-server:
    image: public.ecr.aws/d1q9r5q2/marearts-anpr-server:latest
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ~/.marearts:/root/.marearts
    environment:
      - ANPR_BACKEND=cpu
    restart: unless-stopped
