name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! We'd love to hear your ideas.
        
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform is this feature for?
      options:
        - Mobile App (iOS)
        - Mobile App (Android)
        - Python SDK
        - Docker API
        - All platforms
        - Other
    validations:
      required: true
      
  - type: textarea
    id: problem
    attributes:
      label: Problem / Use Case
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: Describe your ideal solution...
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternatives or workarounds?
      placeholder: Describe any alternative solutions you've considered
      
  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Examples of similar features in other apps/products
      placeholder: App X has a feature like this that works well...
      
  - type: checkboxes
    id: willingness
    attributes:
      label: Contribution
      description: Would you be willing to help implement or test this feature?
      options:
        - label: I can help test this feature
        - label: I can provide more details if needed
        - label: This is critical for my use case

